# Generated by Django 3.2 on 2021-04-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('name_wallet', models.CharField(max_length=50, verbose_name='Имя кошелька')),
                ('wallet_balance', models.FloatField(default=0.0, verbose_name='Баланс кошелька')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.FloatField(default=0.0, max_length=30, verbose_name='Операция')),
                ('date_operations', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время операции')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_wallet.wallet', verbose_name='Кошелек')),
            ],
        ),
    ]
